#Defines whether or not there is a maximum size for each arena. Defaults to false.
hasmax: false

#Maximum size, in blocks, for each arena. Only matters if hasmax is true. Defaults to 0.
maxarenasize: 0
